# -*- coding: utf-8 -*-
"""main_script.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6vCv54I4xZQqxzRsCR4om9xqHUXLOix
"""

# this is Ans Abdullah